### ISSUE TITLE
Java Version Incompatibilities / Documentation

### ISSUE THREAD

**Issue by EngineOfDarkness** [necauqua/starsector-fixes#2]
I'm on Pop!_OS 22.04 LTS (based on Ubuntu)

I've locally tried

1. :x: `OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)`
2. :x: `OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)`
3. :heavy_check_mark: `OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)`

The first two have different failure modes, (the last starts fine):

1. `OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)` causes

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: dev/necauqua/scm/Agent has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Aborted (core dumped)
```

That doesn't seem fixable from an End-User perspective, unless you can compile it for an older version I assume. Not sure if it works even if you could, though.

----

2. `OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)` causes

```
Inconsistency detected by ld.so: dl-lookup.c: 106: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

This seems similar to the one posted in #1 - I found no solution to this online for this java version and according to https://github.com/necauqua/starsector-fixes/issues/1#issuecomment-1345484888 you also cannot say what could be the causes.

**Comment by ChrisDeadman** [comment]
1. yeah I had to compile it myself aswell when I tried with JDK11 because the prebuilt binary is built with JDK15 (as far as I remember) - to compile it just clone the repo and do ``./gradlew clean build`` and it will compile with the JDK you set as default in your OS
2. has nothing todo with starsector-fixes specifically, it's an issue of libgdx and lwjgl (the game engine starsector uses) - [see this post on stackoverflow](https://stackoverflow.com/questions/55847497/how-do-i-troubleshoot-inconsistency-detected-dl-lookup-c-111-java-result-12)

**Comment by necauqua** [comment]
Oh wow yeah I've just compiled it with some jvm without thinking about it too much, I should downgrade the code to java 8 (so that it runs with everything >= jdk8) and compile it with that

**Comment by necauqua** [comment]
well I failed to close the second issue with a commit message, but yeah I've compiled it with jdk 11 (8 does not work because the shim depends on a java 11 library that we're also adding to starsector classpath) and made a new release with that
