### ISSUE TITLE
Incompatible Mod / Documentation

### ISSUE THREAD

**Issue by EngineOfDarkness** [necauqua/starsector-fixes#3]
The following Lib / Mod

- `LazyLib 2.7b` (required by the mod)
  - https://fractalsoftworks.com/forum/index.php?topic=5444.0
- `Persean Chronicles 2.0.3-rc2`
  - https://fractalsoftworks.com/forum/index.php?topic=19830.0

with the following Java Version

```OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)```

causes this crash when creating a new game

```
38425 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
	at org.apache.log4j.Logger.getLogger(Logger.java:107)
	at wisp.questgiver.wispLib.DebugLogger.i(Logger.kt:121)
	at wisp.questgiver.wispLib.DebugLogger.i$default(Logger.kt:33)
	at org.wisp.stories.LifecyclePlugin.readConfiguration(LifecyclePlugin.kt:206)
	at org.wisp.stories.LifecyclePlugin.onGameLoad(LifecyclePlugin.kt:62)
	at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source)
	at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source)
	at com.fs.starfarer.ui.Oo0O.dismiss(Unknown Source)
	at com.fs.starfarer.ui.impl.o0oO.dismiss(Unknown Source)
	at com.fs.starfarer.campaign.save.O0oO.actionPerformed(Unknown Source)
	at com.fs.starfarer.ui.newnew.buttonPressed(Unknown Source)
	at com.fs.starfarer.ui.oooO.Ò00000(Unknown Source)
	at com.fs.starfarer.ui.oooO.processInput(Unknown Source)
	at com.fs.starfarer.ui.V.o00000(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Not using `Persean Chronicles 2.0.3-rc2` (but leaving `LazyLib 2.7b` active) prevents the crash.

----

This is already known by the Mod Author already it seems: https://github.com/wispborne/stories/issues/14 - I'll write a comment there as well.

**Comment by EngineOfDarkness** [comment]
The Mod Author has uploaded a hotfix, see https://github.com/wispborne/stories/issues/14#issuecomment-1356868174

**Comment by necauqua** [comment]
Well duh if something is crashing because of the newer JVM it's absolutely not related to the javaagent that makes one small fix to the base game so that it itself does not crash on said newer JVMs ¯\\\_(ツ)_/¯
