### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by kiritantakechi** [necauqua/starsector-fixes#5]
Can you support arm jvm?
PLZ!

**Comment by necauqua** [comment]
Hi, I've no way of testing that, and I didn't even know if there was an issue with ARM JVMs. Can you share an error at least?

**Comment by kiritantakechi** [comment]
### I successfully ran the game on zulu8 x64 according to your instructions.


Here is the log.

```
0    [main] INFO  com.fs.starfarer.StarfarerLauncher  - Starting Starsector 0.95.1a-RC6 launcher
1    [main] INFO  com.fs.starfarer.StarfarerLauncher  - Running in /Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java
1    [main] INFO  com.fs.starfarer.StarfarerLauncher  - OS: Mac OS X 13.2.1
1    [main] INFO  com.fs.starfarer.StarfarerLauncher  - Java version: 1.8.0_362 (64-bit)
6    [main] INFO  com.fs.starfarer.settings.StarfarerSettings  - Loading settings
9    [main] INFO  com.fs.starfarer.loading.LoadingUtils  - Loading JSON from [ABSOLUTE_AND_CWD: null (data/config/settings.json)]
213  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 1512x982, 120Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 1920x1200, 120Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 1920x1200, 47Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 1920x1200, 60Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 1920x1200, 59Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 1920x1200, 50Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 1920x1200, 48Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1330, 120Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1280, 120Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1330, 47Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1330, 60Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1330, 59Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1330, 48Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1330, 50Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1280, 60Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1280, 59Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1280, 50Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1280, 48Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2048x1280, 47Hz, 32bpp
214  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1432, 48Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1490, 120Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1432, 50Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1432, 59Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1432, 60Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1432, 47Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1490, 59Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1490, 60Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1490, 50Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1432, 120Hz, 32bpp
215  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1490, 48Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2294x1490, 47Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2560x1600, 60Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2560x1600, 59Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2560x1600, 50Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2560x1600, 48Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2560x1600, 47Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2560x1600, 120Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1756, 50Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1756, 48Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1756, 59Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1690, 120Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1756, 60Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1756, 47Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1690, 48Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1690, 50Hz, 32bpp
218  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1690, 60Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1756, 120Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1690, 59Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 2704x1690, 47Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1964, 47Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1964, 50Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1964, 48Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1890, 120Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1964, 59Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1964, 60Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1890, 47Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1890, 60Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1890, 59Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1964, 120Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1890, 48Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Found display mode: 3024x1890, 50Hz, 32bpp
219  [main] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Assuming native monitor resolution is 3024x1964
427  [Thread-3] INFO  com.fs.graphics.float  - Using refresh rate:120
556  [Thread-3] INFO  com.fs.starfarer.launcher.opengl.GLLauncher  - Maximum anti-aliasing samples: 4
707  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/launcher_bg.jpg (using cast)
727  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/launch_button_bg.png (using cast)
733  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/play_button0.png (using cast)
735  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/play_button1.png (using cast)
738  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/buttons/toggleA20x_on.png (using cast)
741  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/buttons/toggleA20x_off.png (using cast)
742  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/buttons/arrow_down.png (using cast)
743  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/fx/scanline11.png (using cast)
745  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/bgs/ui_border1b_e.png (using cast)
746  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/bgs/ui_border1b_e_bot.png (using cast)
747  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/bgs/ui_border1b_e_top.png (using cast)
748  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/bgs/ui_border1b_w.png (using cast)
749  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/bgs/ui_border1b_w_bot.png (using cast)
750  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/ui/bgs/ui_border1b_w_top.png (using cast)
762  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/fonts/orbitron24aabold_0.png (using cast)
788  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/fonts/orbitron20aa_0.png (using cast)
800  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/fonts/insignia15LTaa_0.png (using cast)
835  [Thread-3] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/fonts/orbitron12_0.png (using cast)
```

### However, I encountered issues when switching the JVM to zulu8 arm64.

Here is the error log.


```
0    [main] INFO  com.fs.starfarer.StarfarerLauncher  - Starting Starsector 0.95.1a-RC6 launcher
0    [main] INFO  com.fs.starfarer.StarfarerLauncher  - Running in /Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java
0    [main] INFO  com.fs.starfarer.StarfarerLauncher  - OS: Mac OS X 13.2.1
0    [main] INFO  com.fs.starfarer.StarfarerLauncher  - Java version: 1.8.0_362 (64-bit)
2    [main] INFO  com.fs.starfarer.settings.StarfarerSettings  - Loading settings
3    [main] INFO  com.fs.starfarer.loading.LoadingUtils  - Loading JSON from [ABSOLUTE_AND_CWD: null (data/config/settings.json)]
1202 [main] ERROR com.fs.starfarer.StarfarerLauncher  - java.lang.UnsatisfiedLinkError: /Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib: dlopen(/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib, 0x0001): tried: '/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib' (no such file), '/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64'))
java.lang.UnsatisfiedLinkError: /Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib: dlopen(/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib, 0x0001): tried: '/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib' (no such file), '/Users/kiritan/Downloads/Starsector.app/Contents/Resources/Java/native/macosx/liblwjgl.jnilib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1869)
	at java.lang.Runtime.loadLibrary0(Runtime.java:844)
	at java.lang.System.loadLibrary(System.java:1136)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at com.fs.graphics.DisplayManager.Ò00000(Unknown Source)
	at com.fs.starfarer.launcher.opengl.GLLauncher.detectResolutions(Unknown Source)
	at com.fs.starfarer.launcher.opengl.GLLauncher.<init>(Unknown Source)
	at com.fs.starfarer.launcher.opengl.GLLauncher.createUI(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.<init>(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.<init>(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.main(Unknown Source)

```

**Comment by kiritantakechi** [comment]
The JVM used for the first log is zulu8.68.0.21-ca-jre8.0.362-macosx_x64
The JVM used for the second log is zulu8.68.0.21-ca-jre8.0.362-macosx_aarch64

**Comment by necauqua** [comment]
Oh well from the error it seems that starsector itself (the mac package anyway) does not support arm64, because it only packages the x86_64 version of the LWJGL.

And LWJGL, as I've just googled, only introduced ARM support in version 3.3.0 which is waaaay too recent for starsector to be using :)

So it seems that the game does not support arm64 in principle, until they update that, which they are pretty hesitant to do (why startsector-fixes exists even, they only need to do a couple of little things and people who want newer jvm can have it)

I don't think updating lwjgl (especially since I suspect they use lwjgl2) will be an lucky easy fix like it was with the JVM, so it's probably out of scope for startsector-fixes, sorry

Although I might look into that at some point 🤷

**Comment by kiritantakechi** [comment]
Thank you for your answer！
